import "./globals.css";
import Sidebar from "../components/sidebar";
import Head from "next/head";

const metadata = {
  title: "Alex Martin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  showNavBar = true, // Default value is true, meaning NavBar will be shown by default.
}: {
  children: React.ReactNode;
  showNavBar?: boolean;
}) {
  return (
    <html lang="en" className="min-h-screen">
      <Head>
        <link
          rel="icon"
          href="/icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
      </Head>
      <div className="flex flex-col w-full ">
      <body className="border- antialiased max-w-4xl mb- flex flex-col md:flex-row mx-4 mt-8 md:mt-20 lg:mt-32 lg:mx-auto">
        {showNavBar && <Sidebar />} {/* Conditionally render the NavBar */}
        <main className="flex-auto min-w-0 mt-6 md:mt-0 flex flex-col px-2 md:px-0">
          {children}
          {/* <Analytics /> */}
        </main>
       
      </body>{" "}
      <footer
          className="ml-2 mb-1 md:ml-0 text-center pt-[20px]"
          style={{
            fontSize: "0.75rem",
            bottom: "0",
          }}
        >
          <p> @ Copyright 2024 Alex Martin. Contact: amart50@u.rochester.edu</p>
        </footer>
        </div>
    </html>
  );
}
